# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'author_pages_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpage',
            name='name',
        ),
        migrations.AddField(
            model_name='authorpage',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
