# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('core', '0001_auto_20160705_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
