# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='vector',
            field=models.TextField(help_text=b'SVG contents. It is recommended to use a compressor such as https://jakearchibald.github.io/svgomg/ and remove width/height attributes. It should always have a viewBox attribute.'),
        ),
    ]
