# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:52
from __future__ import unicode_literals

from django.db import migrations


def create_technology(apps, schema_editor):
    Technology = apps.get_model('core', 'Technology')
    TechnologySection = apps.get_model('core', 'TechnologySection')
    for ts in TechnologySection.objects.all():
        if ts.technology_id:
            continue
        ts.technology = Technology.objects.create(
            name=ts.label,
            link=ts.link,
            logo=ts.vector,
        )
        ts.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20160518_2152'),
    ]

    operations = [
        migrations.RunPython(create_technology, migrations.RunPython.noop)
    ]
