# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20160518_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpage',
            name='project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workpage',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.Service'),
        ),
        migrations.AddField(
            model_name='workpage',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='core.Technology'),
        ),
    ]
