# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20160518_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('name',), 'verbose_name_plural': 'technologies'},
        ),
    ]
