# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_author_pages_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
